//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESRI.ArcLogistics.LoadBalanceService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadBalanceResult", Namespace="http://arclogistics.arcgisonline.com/")]
    [System.SerializableAttribute()]
    internal partial class LoadBalanceResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServerUrlField;
        
        private ESRI.ArcLogistics.LoadBalanceService.StatusCode StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string ServerUrl {
            get {
                return this.ServerUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerUrlField, value) != true)) {
                    this.ServerUrlField = value;
                    this.RaisePropertyChanged("ServerUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal ESRI.ArcLogistics.LoadBalanceService.StatusCode Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusCode", Namespace="http://arclogistics.arcgisonline.com/")]
    internal enum StatusCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Succeed = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoServerAvailable = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://arclogistics.arcgisonline.com/", ConfigurationName="LoadBalanceService.LoadBalanceServiceSoap")]
    internal interface LoadBalanceServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetServiceUrlResult from namespace http://arclogistics.arcgisonline.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://arclogistics.arcgisonline.com/GetServiceUrl", ReplyAction="*")]
        ESRI.ArcLogistics.LoadBalanceService.GetServiceUrlResponse GetServiceUrl(ESRI.ArcLogistics.LoadBalanceService.GetServiceUrlRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetServiceUrlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServiceUrl", Namespace="http://arclogistics.arcgisonline.com/", Order=0)]
        public ESRI.ArcLogistics.LoadBalanceService.GetServiceUrlRequestBody Body;
        
        public GetServiceUrlRequest() {
        }
        
        public GetServiceUrlRequest(ESRI.ArcLogistics.LoadBalanceService.GetServiceUrlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class GetServiceUrlRequestBody {
        
        public GetServiceUrlRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetServiceUrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServiceUrlResponse", Namespace="http://arclogistics.arcgisonline.com/", Order=0)]
        public ESRI.ArcLogistics.LoadBalanceService.GetServiceUrlResponseBody Body;
        
        public GetServiceUrlResponse() {
        }
        
        public GetServiceUrlResponse(ESRI.ArcLogistics.LoadBalanceService.GetServiceUrlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://arclogistics.arcgisonline.com/")]
    internal partial class GetServiceUrlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ESRI.ArcLogistics.LoadBalanceService.LoadBalanceResult GetServiceUrlResult;
        
        public GetServiceUrlResponseBody() {
        }
        
        public GetServiceUrlResponseBody(ESRI.ArcLogistics.LoadBalanceService.LoadBalanceResult GetServiceUrlResult) {
            this.GetServiceUrlResult = GetServiceUrlResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface LoadBalanceServiceSoapChannel : ESRI.ArcLogistics.LoadBalanceService.LoadBalanceServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class LoadBalanceServiceSoapClient : System.ServiceModel.ClientBase<ESRI.ArcLogistics.LoadBalanceService.LoadBalanceServiceSoap>, ESRI.ArcLogistics.LoadBalanceService.LoadBalanceServiceSoap {
        
        public LoadBalanceServiceSoapClient() {
        }
        
        public LoadBalanceServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoadBalanceServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoadBalanceServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoadBalanceServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESRI.ArcLogistics.LoadBalanceService.GetServiceUrlResponse ESRI.ArcLogistics.LoadBalanceService.LoadBalanceServiceSoap.GetServiceUrl(ESRI.ArcLogistics.LoadBalanceService.GetServiceUrlRequest request) {
            return base.Channel.GetServiceUrl(request);
        }
        
        public ESRI.ArcLogistics.LoadBalanceService.LoadBalanceResult GetServiceUrl() {
            ESRI.ArcLogistics.LoadBalanceService.GetServiceUrlRequest inValue = new ESRI.ArcLogistics.LoadBalanceService.GetServiceUrlRequest();
            inValue.Body = new ESRI.ArcLogistics.LoadBalanceService.GetServiceUrlRequestBody();
            ESRI.ArcLogistics.LoadBalanceService.GetServiceUrlResponse retVal = ((ESRI.ArcLogistics.LoadBalanceService.LoadBalanceServiceSoap)(this)).GetServiceUrl(inValue);
            return retVal.Body.GetServiceUrlResult;
        }
    }
}
