// APIREV: make internal
/*
 | Version 10.1.84
 | Copyright 2013 Esri
 |
 | Licensed under the Apache License, Version 2.0 (the "License");
 | you may not use this file except in compliance with the License.
 | You may obtain a copy of the License at
 |
 |    http://www.apache.org/licenses/LICENSE-2.0
 |
 | Unless required by applicable law or agreed to in writing, software
 | distributed under the License is distributed on an "AS IS" BASIS,
 | WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 | See the License for the specific language governing permissions and
 | limitations under the License.
 */

using System;
namespace ESRI.ArcLogistics.Data.DataModel
{
    ///////////////////////////////////////////////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////////////////////

    // The following partial classes extend autogenerated entity classes.

    ///////////////////////////////////////////////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////////////////////

    public partial class Drivers : IWrapDataAccess, IDataObject
    {
        public DataObject DataObject { get; set; }
    }

    public partial class DriverSpecialties : IWrapDataAccess, IDataObject
    {
        public DataObject DataObject { get; set; }
    }

    public partial class FuelTypes : IWrapDataAccess, IDataObject
    {
        public DataObject DataObject { get; set; }
    }

    public partial class Locations : IWrapDataAccess, IDataObject
    {
        public DataObject DataObject { get; set; }
    }

    public partial class MobileDevices : IWrapDataAccess, IDataObject
    {
        public DataObject DataObject { get; set; }
    }

    public partial class Vehicles : IWrapDataAccess, IDataObject
    {
        public DataObject DataObject { get; set; }
    }

    public partial class VehicleSpecialties : IWrapDataAccess, IDataObject
    {
        public DataObject DataObject { get; set; }
    }

    public partial class Routes : IWrapDataAccess, IDataObject
    {
        public DataObject DataObject { get; set; }
    }

    public partial class Orders : IWrapDataAccess, IDataObject
    {
        public DataObject DataObject { get; set; }
    }

    public partial class Schedules : IWrapDataAccess, IDataObject
    {
        public DataObject DataObject { get; set; }
    }

    public partial class Stops : IWrapDataAccess, IDataObject
    {
        public DataObject DataObject { get; set; }
    }

    public partial class Barriers : IWrapDataAccess, IDataObject
    {
        public DataObject DataObject { get; set; }
    }

    public partial class Zones : IWrapDataAccess, IDataObject
    {
        public DataObject DataObject { get; set; }
    }
}
