// APIREV: make internal
using System;
namespace ESRI.ArcLogistics.Data.DataModel
{
    ///////////////////////////////////////////////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////////////////////

    // The following partial classes extend autogenerated entity classes.

    ///////////////////////////////////////////////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////////////////////

    public partial class Drivers : IWrapDataAccess, IDataObject
    {
        public DataObject DataObject { get; set; }
    }

    public partial class DriverSpecialties : IWrapDataAccess, IDataObject
    {
        public DataObject DataObject { get; set; }
    }

    public partial class FuelTypes : IWrapDataAccess, IDataObject
    {
        public DataObject DataObject { get; set; }
    }

    public partial class Locations : IWrapDataAccess, IDataObject
    {
        public DataObject DataObject { get; set; }
    }

    public partial class MobileDevices : IWrapDataAccess, IDataObject
    {
        public DataObject DataObject { get; set; }
    }

    public partial class Vehicles : IWrapDataAccess, IDataObject
    {
        public DataObject DataObject { get; set; }
    }

    public partial class VehicleSpecialties : IWrapDataAccess, IDataObject
    {
        public DataObject DataObject { get; set; }
    }

    public partial class Routes : IWrapDataAccess, IDataObject
    {
        public DataObject DataObject { get; set; }
    }

    public partial class Orders : IWrapDataAccess, IDataObject
    {
        public DataObject DataObject { get; set; }
    }

    public partial class Schedules : IWrapDataAccess, IDataObject
    {
        public DataObject DataObject { get; set; }
    }

    public partial class Stops : IWrapDataAccess, IDataObject
    {
        public DataObject DataObject { get; set; }
    }

    public partial class Barriers : IWrapDataAccess, IDataObject
    {
        public DataObject DataObject { get; set; }
    }

    public partial class Zones : IWrapDataAccess, IDataObject
    {
        public DataObject DataObject { get; set; }
    }
}
