//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESRI.ArcLogistics.CatalogService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/10.0", ConfigurationName="CatalogService.ServiceCatalogPort")]
    internal interface ServiceCatalogPort {
        
        // CODEGEN: Parameter 'MessageVersion' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="MessageVersion")]
        ESRI.ArcLogistics.CatalogService.GetMessageVersionResponse GetMessageVersion(ESRI.ArcLogistics.CatalogService.GetMessageVersionRequest request);
        
        // CODEGEN: Parameter 'MessageFormats' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="MessageFormats")]
        ESRI.ArcLogistics.CatalogService.GetMessageFormatsResponse GetMessageFormats(ESRI.ArcLogistics.CatalogService.GetMessageFormatsRequest request);
        
        // CODEGEN: Parameter 'TokenServiceURL' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="TokenServiceURL")]
        ESRI.ArcLogistics.CatalogService.GetTokenServiceURLResponse GetTokenServiceURL(ESRI.ArcLogistics.CatalogService.GetTokenServiceURLRequest request);
        
        // CODEGEN: Parameter 'FolderNames' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="FolderNames")]
        ESRI.ArcLogistics.CatalogService.GetFoldersResponse GetFolders(ESRI.ArcLogistics.CatalogService.GetFoldersRequest request);
        
        // CODEGEN: Parameter 'ServiceDescriptions' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ServiceDescriptions")]
        ESRI.ArcLogistics.CatalogService.GetServiceDescriptionsResponse GetServiceDescriptions(ESRI.ArcLogistics.CatalogService.GetServiceDescriptionsRequest request);
        
        // CODEGEN: Parameter 'Result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        ESRI.ArcLogistics.CatalogService.RequiresTokensResponse RequiresTokens(ESRI.ArcLogistics.CatalogService.RequiresTokensRequest request);
        
        // CODEGEN: Parameter 'ServiceDescriptions' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ServiceDescriptions")]
        ESRI.ArcLogistics.CatalogService.GetServiceDescriptionsExResponse GetServiceDescriptionsEx(ESRI.ArcLogistics.CatalogService.GetServiceDescriptionsExRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/10.0")]
    public enum esriArcGISVersion {
        
        /// <remarks/>
        esriArcGISVersion83,
        
        /// <remarks/>
        esriArcGISVersion90,
        
        /// <remarks/>
        esriArcGISVersion92,
        
        /// <remarks/>
        esriArcGISVersion93,
        
        /// <remarks/>
        esriArcGISVersion10,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageVersion", WrapperNamespace="http://www.esri.com/schemas/ArcGIS/10.0", IsWrapped=true)]
    internal partial class GetMessageVersionRequest {
        
        public GetMessageVersionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageVersionResponse", WrapperNamespace="http://www.esri.com/schemas/ArcGIS/10.0", IsWrapped=true)]
    internal partial class GetMessageVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/10.0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESRI.ArcLogistics.CatalogService.esriArcGISVersion MessageVersion;
        
        public GetMessageVersionResponse() {
        }
        
        public GetMessageVersionResponse(ESRI.ArcLogistics.CatalogService.esriArcGISVersion MessageVersion) {
            this.MessageVersion = MessageVersion;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/10.0")]
    public enum esriServiceCatalogMessageFormat {
        
        /// <remarks/>
        esriServiceCatalogMessageFormatSoap,
        
        /// <remarks/>
        esriServiceCatalogMessageFormatBin,
        
        /// <remarks/>
        esriServiceCatalogMessageFormatSoapOrBin,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageFormats", WrapperNamespace="http://www.esri.com/schemas/ArcGIS/10.0", IsWrapped=true)]
    internal partial class GetMessageFormatsRequest {
        
        public GetMessageFormatsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageFormatsResponse", WrapperNamespace="http://www.esri.com/schemas/ArcGIS/10.0", IsWrapped=true)]
    internal partial class GetMessageFormatsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/10.0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESRI.ArcLogistics.CatalogService.esriServiceCatalogMessageFormat MessageFormats;
        
        public GetMessageFormatsResponse() {
        }
        
        public GetMessageFormatsResponse(ESRI.ArcLogistics.CatalogService.esriServiceCatalogMessageFormat MessageFormats) {
            this.MessageFormats = MessageFormats;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTokenServiceURL", WrapperNamespace="http://www.esri.com/schemas/ArcGIS/10.0", IsWrapped=true)]
    internal partial class GetTokenServiceURLRequest {
        
        public GetTokenServiceURLRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTokenServiceURLResponse", WrapperNamespace="http://www.esri.com/schemas/ArcGIS/10.0", IsWrapped=true)]
    internal partial class GetTokenServiceURLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/10.0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TokenServiceURL;
        
        public GetTokenServiceURLResponse() {
        }
        
        public GetTokenServiceURLResponse(string TokenServiceURL) {
            this.TokenServiceURL = TokenServiceURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFolders", WrapperNamespace="http://www.esri.com/schemas/ArcGIS/10.0", IsWrapped=true)]
    internal partial class GetFoldersRequest {
        
        public GetFoldersRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFoldersResponse", WrapperNamespace="http://www.esri.com/schemas/ArcGIS/10.0", IsWrapped=true)]
    internal partial class GetFoldersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/10.0", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("String", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] FolderNames;
        
        public GetFoldersResponse() {
        }
        
        public GetFoldersResponse(string[] FolderNames) {
            this.FolderNames = FolderNames;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/10.0")]
    public partial class ServiceDescription : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string typeField;
        
        private string urlField;
        
        private string parentTypeField;
        
        private string capabilitiesField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("Url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ParentType {
            get {
                return this.parentTypeField;
            }
            set {
                this.parentTypeField = value;
                this.RaisePropertyChanged("ParentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Capabilities {
            get {
                return this.capabilitiesField;
            }
            set {
                this.capabilitiesField = value;
                this.RaisePropertyChanged("Capabilities");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServiceDescriptions", WrapperNamespace="http://www.esri.com/schemas/ArcGIS/10.0", IsWrapped=true)]
    internal partial class GetServiceDescriptionsRequest {
        
        public GetServiceDescriptionsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServiceDescriptionsResponse", WrapperNamespace="http://www.esri.com/schemas/ArcGIS/10.0", IsWrapped=true)]
    internal partial class GetServiceDescriptionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/10.0", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ServiceDescription[] ServiceDescriptions;
        
        public GetServiceDescriptionsResponse() {
        }
        
        public GetServiceDescriptionsResponse(ServiceDescription[] ServiceDescriptions) {
            this.ServiceDescriptions = ServiceDescriptions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequiresTokens", WrapperNamespace="http://www.esri.com/schemas/ArcGIS/10.0", IsWrapped=true)]
    internal partial class RequiresTokensRequest {
        
        public RequiresTokensRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequiresTokensResponse", WrapperNamespace="http://www.esri.com/schemas/ArcGIS/10.0", IsWrapped=true)]
    internal partial class RequiresTokensResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/10.0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Result;
        
        public RequiresTokensResponse() {
        }
        
        public RequiresTokensResponse(bool Result) {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServiceDescriptionsEx", WrapperNamespace="http://www.esri.com/schemas/ArcGIS/10.0", IsWrapped=true)]
    internal partial class GetServiceDescriptionsExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/10.0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FolderName;
        
        public GetServiceDescriptionsExRequest() {
        }
        
        public GetServiceDescriptionsExRequest(string FolderName) {
            this.FolderName = FolderName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServiceDescriptionsExResponse", WrapperNamespace="http://www.esri.com/schemas/ArcGIS/10.0", IsWrapped=true)]
    internal partial class GetServiceDescriptionsExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/10.0", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ServiceDescription[] ServiceDescriptions;
        
        public GetServiceDescriptionsExResponse() {
        }
        
        public GetServiceDescriptionsExResponse(ServiceDescription[] ServiceDescriptions) {
            this.ServiceDescriptions = ServiceDescriptions;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface ServiceCatalogPortChannel : ESRI.ArcLogistics.CatalogService.ServiceCatalogPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class ServiceCatalogPortClient : System.ServiceModel.ClientBase<ESRI.ArcLogistics.CatalogService.ServiceCatalogPort>, ESRI.ArcLogistics.CatalogService.ServiceCatalogPort {
        
        public ServiceCatalogPortClient() {
        }
        
        public ServiceCatalogPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCatalogPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCatalogPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCatalogPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESRI.ArcLogistics.CatalogService.GetMessageVersionResponse ESRI.ArcLogistics.CatalogService.ServiceCatalogPort.GetMessageVersion(ESRI.ArcLogistics.CatalogService.GetMessageVersionRequest request) {
            return base.Channel.GetMessageVersion(request);
        }
        
        public ESRI.ArcLogistics.CatalogService.esriArcGISVersion GetMessageVersion() {
            ESRI.ArcLogistics.CatalogService.GetMessageVersionRequest inValue = new ESRI.ArcLogistics.CatalogService.GetMessageVersionRequest();
            ESRI.ArcLogistics.CatalogService.GetMessageVersionResponse retVal = ((ESRI.ArcLogistics.CatalogService.ServiceCatalogPort)(this)).GetMessageVersion(inValue);
            return retVal.MessageVersion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESRI.ArcLogistics.CatalogService.GetMessageFormatsResponse ESRI.ArcLogistics.CatalogService.ServiceCatalogPort.GetMessageFormats(ESRI.ArcLogistics.CatalogService.GetMessageFormatsRequest request) {
            return base.Channel.GetMessageFormats(request);
        }
        
        public ESRI.ArcLogistics.CatalogService.esriServiceCatalogMessageFormat GetMessageFormats() {
            ESRI.ArcLogistics.CatalogService.GetMessageFormatsRequest inValue = new ESRI.ArcLogistics.CatalogService.GetMessageFormatsRequest();
            ESRI.ArcLogistics.CatalogService.GetMessageFormatsResponse retVal = ((ESRI.ArcLogistics.CatalogService.ServiceCatalogPort)(this)).GetMessageFormats(inValue);
            return retVal.MessageFormats;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESRI.ArcLogistics.CatalogService.GetTokenServiceURLResponse ESRI.ArcLogistics.CatalogService.ServiceCatalogPort.GetTokenServiceURL(ESRI.ArcLogistics.CatalogService.GetTokenServiceURLRequest request) {
            return base.Channel.GetTokenServiceURL(request);
        }
        
        public string GetTokenServiceURL() {
            ESRI.ArcLogistics.CatalogService.GetTokenServiceURLRequest inValue = new ESRI.ArcLogistics.CatalogService.GetTokenServiceURLRequest();
            ESRI.ArcLogistics.CatalogService.GetTokenServiceURLResponse retVal = ((ESRI.ArcLogistics.CatalogService.ServiceCatalogPort)(this)).GetTokenServiceURL(inValue);
            return retVal.TokenServiceURL;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESRI.ArcLogistics.CatalogService.GetFoldersResponse ESRI.ArcLogistics.CatalogService.ServiceCatalogPort.GetFolders(ESRI.ArcLogistics.CatalogService.GetFoldersRequest request) {
            return base.Channel.GetFolders(request);
        }
        
        public string[] GetFolders() {
            ESRI.ArcLogistics.CatalogService.GetFoldersRequest inValue = new ESRI.ArcLogistics.CatalogService.GetFoldersRequest();
            ESRI.ArcLogistics.CatalogService.GetFoldersResponse retVal = ((ESRI.ArcLogistics.CatalogService.ServiceCatalogPort)(this)).GetFolders(inValue);
            return retVal.FolderNames;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESRI.ArcLogistics.CatalogService.GetServiceDescriptionsResponse ESRI.ArcLogistics.CatalogService.ServiceCatalogPort.GetServiceDescriptions(ESRI.ArcLogistics.CatalogService.GetServiceDescriptionsRequest request) {
            return base.Channel.GetServiceDescriptions(request);
        }
        
        public ServiceDescription[] GetServiceDescriptions() {
            ESRI.ArcLogistics.CatalogService.GetServiceDescriptionsRequest inValue = new ESRI.ArcLogistics.CatalogService.GetServiceDescriptionsRequest();
            ESRI.ArcLogistics.CatalogService.GetServiceDescriptionsResponse retVal = ((ESRI.ArcLogistics.CatalogService.ServiceCatalogPort)(this)).GetServiceDescriptions(inValue);
            return retVal.ServiceDescriptions;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESRI.ArcLogistics.CatalogService.RequiresTokensResponse ESRI.ArcLogistics.CatalogService.ServiceCatalogPort.RequiresTokens(ESRI.ArcLogistics.CatalogService.RequiresTokensRequest request) {
            return base.Channel.RequiresTokens(request);
        }
        
        public bool RequiresTokens() {
            ESRI.ArcLogistics.CatalogService.RequiresTokensRequest inValue = new ESRI.ArcLogistics.CatalogService.RequiresTokensRequest();
            ESRI.ArcLogistics.CatalogService.RequiresTokensResponse retVal = ((ESRI.ArcLogistics.CatalogService.ServiceCatalogPort)(this)).RequiresTokens(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESRI.ArcLogistics.CatalogService.GetServiceDescriptionsExResponse ESRI.ArcLogistics.CatalogService.ServiceCatalogPort.GetServiceDescriptionsEx(ESRI.ArcLogistics.CatalogService.GetServiceDescriptionsExRequest request) {
            return base.Channel.GetServiceDescriptionsEx(request);
        }
        
        public ServiceDescription[] GetServiceDescriptionsEx(string FolderName) {
            ESRI.ArcLogistics.CatalogService.GetServiceDescriptionsExRequest inValue = new ESRI.ArcLogistics.CatalogService.GetServiceDescriptionsExRequest();
            inValue.FolderName = FolderName;
            ESRI.ArcLogistics.CatalogService.GetServiceDescriptionsExResponse retVal = ((ESRI.ArcLogistics.CatalogService.ServiceCatalogPort)(this)).GetServiceDescriptionsEx(inValue);
            return retVal.ServiceDescriptions;
        }
    }
}
