//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcLogisticsPlugIns.Properties {
    /*
 | Version 10.1.84
 | Copyright 2013 Esri
 |
 | Licensed under the Apache License, Version 2.0 (the "License");
 | you may not use this file except in compliance with the License.
 | You may obtain a copy of the License at
 |
 |    http://www.apache.org/licenses/LICENSE-2.0
 |
 | Unless required by applicable law or agreed to in writing, software
 | distributed under the License is distributed on an "AS IS" BASIS,
 | WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 | See the License for the specific language governing permissions and
 | limitations under the License.
 */

using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArcLogisticsPlugIns.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active sync profile is required..
        /// </summary>
        public static string ActiveSyncProfileEmpty {
            get {
                return ResourceManager.GetString("ActiveSyncProfileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All routes sent..
        /// </summary>
        public static string AllRoutesSent {
            get {
                return ResourceManager.GetString("AllRoutesSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled by user..
        /// </summary>
        public static string CanceledByUser {
            get {
                return ResourceManager.GetString("CanceledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButtonCaption {
            get {
                return ResourceManager.GetString("CloseButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device {0} not found..
        /// </summary>
        public static string DeviceNotFound {
            get {
                return ResourceManager.GetString("DeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server requires an encrypted connection (SSL).
        /// </summary>
        public static string EncryptedConnectionRequiresCheckBoxContent {
            get {
                return ResourceManager.GetString("EncryptedConnectionRequiresCheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To Navigator action panel..
        /// </summary>
        public static string ExportToNavigatorLink {
            get {
                return ResourceManager.GetString("ExportToNavigatorLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send routes..
        /// </summary>
        public static string FailedToSendRoutes {
            get {
                return ResourceManager.GetString("FailedToSendRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder path is required..
        /// </summary>
        public static string FolderPathEmpty {
            get {
                return ResourceManager.GetString("FolderPathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Route for {0} on {1}.&quot;.
        /// </summary>
        public static string GRFLetterSubjectFormat {
            get {
                return ResourceManager.GetString("GRFLetterSubjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail address is required..
        /// </summary>
        public static string MailAddressEmpty {
            get {
                return ResourceManager.GetString("MailAddressEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your E-Mail settings and E-Mail server connection..
        /// </summary>
        public static string MailConnectionError {
            get {
                return ResourceManager.GetString("MailConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail setting not complete. Please setup them correctly on.
        /// </summary>
        public static string MailerSettingsEmpty {
            get {
                return ResourceManager.GetString("MailerSettingsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail to: {0}.
        /// </summary>
        public static string MailToFormat {
            get {
                return ResourceManager.GetString("MailToFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Routes.
        /// </summary>
        public static string ManageSendRoutesCommandTitle {
            get {
                return ResourceManager.GetString("ManageSendRoutesCommandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mobile device isn&apos;t selected for a vehicle or a driver on this route..
        /// </summary>
        public static string MobileDeviceEmpty {
            get {
                return ResourceManager.GetString("MobileDeviceEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkButtonCaption {
            get {
                return ResourceManager.GetString("OkButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string PasswordLabelContent {
            get {
                return ResourceManager.GetString("PasswordLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string PortLabelContent {
            get {
                return ResourceManager.GetString("PortLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Password.
        /// </summary>
        public static string RememberPasswordCheckBoxContent {
            get {
                return ResourceManager.GetString("RememberPasswordCheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress route GRF.
        /// </summary>
        public static string RouteGRFcompressionCheckBoxContent {
            get {
                return ResourceManager.GetString("RouteGRFcompressionCheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route.
        /// </summary>
        public static string RouteNameColumnTitle {
            get {
                return ResourceManager.GetString("RouteNameColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} routes sent..
        /// </summary>
        public static string RoutesSent {
            get {
                return ResourceManager.GetString("RoutesSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to folder: {0}.
        /// </summary>
        public static string SaveToFormat {
            get {
                return ResourceManager.GetString("SaveToFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Routes.
        /// </summary>
        public static string SendButtonCaption {
            get {
                return ResourceManager.GetString("SendButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending GRF for route &quot;{0}&quot; failed. {1}.
        /// </summary>
        public static string SendingFailed {
            get {
                return ResourceManager.GetString("SendingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending GRF failed..
        /// </summary>
        public static string SendingFailedMessage {
            get {
                return ResourceManager.GetString("SendingFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending routes.
        /// </summary>
        public static string SendingRoutes {
            get {
                return ResourceManager.GetString("SendingRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Method.
        /// </summary>
        public static string SendMethodColumnTitle {
            get {
                return ResourceManager.GetString("SendMethodColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one route to send routes to navigator.
        /// </summary>
        public static string SendRoutesCommandDisabledTooltip {
            get {
                return ResourceManager.GetString("SendRoutesCommandDisabledTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports routes to mobile device(s) for use with ArcLogistics Navigator.
        /// </summary>
        public static string SendRoutesCommandEnabledTooltip {
            get {
                return ResourceManager.GetString("SendRoutesCommandEnabledTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Routes to Navigator.
        /// </summary>
        public static string SendRoutesPageCaption {
            get {
                return ResourceManager.GetString("SendRoutesPageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the routes to send to the ArcLogistics Navigator. You can see the status of the transfer in the Send Status area. The next step is to generate reports or begin work on the next schedule..
        /// </summary>
        public static string SendRoutesPageQuickHelp {
            get {
                return ResourceManager.GetString("SendRoutesPageQuickHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Route.
        /// </summary>
        public static string SendRoutesStepCaption {
            get {
                return ResourceManager.GetString("SendRoutesStepCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To Navigator.
        /// </summary>
        public static string SendRoutesToNavigatorTitle {
            get {
                return ResourceManager.GetString("SendRoutesToNavigatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Address:.
        /// </summary>
        public static string ServerAddressLabelContent {
            get {
                return ResourceManager.GetString("ServerAddressLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string ServerLabelContent {
            get {
                return ResourceManager.GetString("ServerLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server requires authentication.
        /// </summary>
        public static string ServerRequiresAutenticationCheckBoxContent {
            get {
                return ResourceManager.GetString("ServerRequiresAutenticationCheckBoxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route {0} successfully mailed to: {1}..
        /// </summary>
        public static string SuccessfullyMailed {
            get {
                return ResourceManager.GetString("SuccessfullyMailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route {0} successfully sent to &quot;{1}&quot; device..
        /// </summary>
        public static string SuccessfullySentToDevice {
            get {
                return ResourceManager.GetString("SuccessfullySentToDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route {0} successfully sent to folder: {1}..
        /// </summary>
        public static string SuccessfullySentToFolder {
            get {
                return ResourceManager.GetString("SuccessfullySentToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing via Active Sync with &quot;{0}&quot; device.
        /// </summary>
        public static string SyncingToFormat {
            get {
                return ResourceManager.GetString("SyncingToFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File synchronization is not activated for {0} device..
        /// </summary>
        public static string SyncPathAbsent {
            get {
                return ResourceManager.GetString("SyncPathAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile device sync type is not supported..
        /// </summary>
        public static string SyncTypeIsNotSupported {
            get {
                return ResourceManager.GetString("SyncTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync type is not selected for the mobile device assigned to the driver on this route..
        /// </summary>
        public static string SyncTypeNotSelectedForDriverDevice {
            get {
                return ResourceManager.GetString("SyncTypeNotSelectedForDriverDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync type is not selected for the mobile device assigned to the vehicle on this route..
        /// </summary>
        public static string SyncTypeNotSelectedForVehicleDevice {
            get {
                return ResourceManager.GetString("SyncTypeNotSelectedForVehicleDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your password..
        /// </summary>
        public static string TypePasswordLabelContent {
            get {
                return ResourceManager.GetString("TypePasswordLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name:.
        /// </summary>
        public static string UserNameLabelContent {
            get {
                return ResourceManager.GetString("UserNameLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be empty..
        /// </summary>
        public static string ValueCannotBeEmpty {
            get {
                return ResourceManager.GetString("ValueCannotBeEmpty", resourceCulture);
            }
        }
    }
}
