//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESRI.ArcLogistics.Properties {
    /*
 | Version 10.1.84
 | Copyright 2013 Esri
 |
 | Licensed under the Apache License, Version 2.0 (the "License");
 | you may not use this file except in compliance with the License.
 | You may obtain a copy of the License at
 |
 |    http://www.apache.org/licenses/LICENSE-2.0
 |
 | Unless required by applicable law or agreed to in writing, software
 | distributed under the License is distributed on an "AS IS" BASIS,
 | WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 | See the License for the specific language governing permissions and
 | limitations under the License.
 */

using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESRI.ArcLogistics.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get status for job {0}..
        /// </summary>
        internal static string Erorr_GetJobResult {
            get {
                return ResourceManager.GetString("Erorr_GetJobResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fields found in table &apos;{0}&apos; to export..
        /// </summary>
        internal static string Error_AbsentFieldsInTable {
            get {
                return ResourceManager.GetString("Error_AbsentFieldsInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Server returned: {1}.
        /// </summary>
        internal static string Error_ArcgisRestError {
            get {
                return ResourceManager.GetString("Error_ArcgisRestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Server returned unspecified error with code {1}..
        /// </summary>
        internal static string Error_ArcgisRestUnspecifiedError {
            get {
                return ResourceManager.GetString("Error_ArcgisRestUnspecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be of type {0}..
        /// </summary>
        internal static string Error_ArgumentMustBeOfType {
            get {
                return ResourceManager.GetString("Error_ArgumentMustBeOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either start or finish date must be not null..
        /// </summary>
        internal static string Error_ArgumentsNullException {
            get {
                return ResourceManager.GetString("Error_ArgumentsNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to format attribute parameters..
        /// </summary>
        internal static string Error_AttrParametersFormat {
            get {
                return ResourceManager.GetString("Error_AttrParametersFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert attribute to object id..
        /// </summary>
        internal static string Error_AttrToObjectIdConvertFailed {
            get {
                return ResourceManager.GetString("Error_AttrToObjectIdConvertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the breaks must have the same type..
        /// </summary>
        internal static string Error_BreaksHaveDifferentTypes {
            get {
                return ResourceManager.GetString("Error_BreaksHaveDifferentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to build path for stop..
        /// </summary>
        internal static string Error_BuildStopPathFailed {
            get {
                return ResourceManager.GetString("Error_BuildStopPathFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} service url retrieval failed with error code &apos;{1}&apos;..
        /// </summary>
        internal static string Error_CannotRetrieveServiceUrl {
            get {
                return ResourceManager.GetString("Error_CannotRetrieveServiceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert compact geometry..
        /// </summary>
        internal static string Error_CompactGeometryConversion {
            get {
                return ResourceManager.GetString("Error_CompactGeometryConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load configuration scheme (id={0})..
        /// </summary>
        internal static string Error_ConfigSchemeLoadFailed {
            get {
                return ResourceManager.GetString("Error_ConfigSchemeLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create data object..
        /// </summary>
        internal static string Error_CreateDataObjectFailed {
            get {
                return ResourceManager.GetString("Error_CreateDataObjectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependecies for property &apos;{0}&apos; contains a cycle &apos;{1}&apos;..
        /// </summary>
        internal static string Error_CycleInPropertyDependencies {
            get {
                return ResourceManager.GetString("Error_CycleInPropertyDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update database..
        /// </summary>
        internal static string Error_DatabaseUpdate {
            get {
                return ResourceManager.GetString("Error_DatabaseUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data object already exists in the collection..
        /// </summary>
        internal static string Error_DataObjectExistsInCollection {
            get {
                return ResourceManager.GetString("Error_DataObjectExistsInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data object does not conform to collection&apos;s filtration clause..
        /// </summary>
        internal static string Error_DataObjectRejectedByFilter {
            get {
                return ResourceManager.GetString("Error_DataObjectRejectedByFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data object cannot be removed..
        /// </summary>
        internal static string Error_DataObjectRemovalFailed {
            get {
                return ResourceManager.GetString("Error_DataObjectRemovalFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database file with the specified path already exists..
        /// </summary>
        internal static string Error_DbFileExists {
            get {
                return ResourceManager.GetString("Error_DbFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open database since the file is in use..
        /// </summary>
        internal static string Error_DbFileSharingViolation {
            get {
                return ResourceManager.GetString("Error_DbFileSharingViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver is already in use for other route(s). Please check that routes with the same driver have different dates or times..
        /// </summary>
        internal static string Error_DefaultRouteContainsInvalidDriver {
            get {
                return ResourceManager.GetString("Error_DefaultRouteContainsInvalidDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle is already in use for other route(s). Please check that routes with the same vehicle have different dates or times..
        /// </summary>
        internal static string Error_DefaultRouteContainsInvalidVehicle {
            get {
                return ResourceManager.GetString("Error_DefaultRouteContainsInvalidVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &quot;{1}&quot; already exists. Please enter another name..
        /// </summary>
        internal static string Error_DuplicateName {
            get {
                return ResourceManager.GetString("Error_DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data object is not attached to data a object context..
        /// </summary>
        internal static string Error_EntityDetached {
            get {
                return ResourceManager.GetString("Error_EntityDetached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to apply edits to the \&quot;{0}\&quot; layer..
        /// </summary>
        internal static string Error_FeatureLayerCannotApplyEdits {
            get {
                return ResourceManager.GetString("Error_FeatureLayerCannotApplyEdits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified feature layer name cannot be found in the feature service..
        /// </summary>
        internal static string Error_FeatureServiceUnknownLayerName {
            get {
                return ResourceManager.GetString("Error_FeatureServiceUnknownLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date must be the same or later than the From date..
        /// </summary>
        internal static string Error_FromDateLaterToDate {
            get {
                return ResourceManager.GetString("Error_FromDateLaterToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate the archive database name..
        /// </summary>
        internal static string Error_GenDBArchiveName {
            get {
                return ResourceManager.GetString("Error_GenDBArchiveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get attribute by the specified key value..
        /// </summary>
        internal static string Error_GetAttributeByKeyFailed {
            get {
                return ResourceManager.GetString("Error_GetAttributeByKeyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the data object cache..
        /// </summary>
        internal static string Error_GetCacheFailed {
            get {
                return ResourceManager.GetString("Error_GetCacheFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get driving directions..
        /// </summary>
        internal static string Error_GetDirections {
            get {
                return ResourceManager.GetString("Error_GetDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the discovery service configuration..
        /// </summary>
        internal static string Error_GetDiscoveryServiceConfigFailed {
            get {
                return ResourceManager.GetString("Error_GetDiscoveryServiceConfigFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the geocoding services configuration..
        /// </summary>
        internal static string Error_GetGeocodeServicesConfigFailed {
            get {
                return ResourceManager.GetString("Error_GetGeocodeServicesConfigFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve a GP parameter value for job {0}..
        /// </summary>
        internal static string Error_GetJobParameter {
            get {
                return ResourceManager.GetString("Error_GetJobParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the data object id value..
        /// </summary>
        internal static string Error_GetKeyFailed {
            get {
                return ResourceManager.GetString("Error_GetKeyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the map services configuration..
        /// </summary>
        internal static string Error_GetMapServicesConfigFailed {
            get {
                return ResourceManager.GetString("Error_GetMapServicesConfigFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the project version..
        /// </summary>
        internal static string Error_GetProjectVersionFailed {
            get {
                return ResourceManager.GetString("Error_GetProjectVersionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the routing services configuration..
        /// </summary>
        internal static string Error_GetRouteServicesConfigFailed {
            get {
                return ResourceManager.GetString("Error_GetRouteServicesConfigFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the server configuration..
        /// </summary>
        internal static string Error_GetServersConfigFailed {
            get {
                return ResourceManager.GetString("Error_GetServersConfigFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the upgrade script for required the database scheme version..
        /// </summary>
        internal static string Error_GetUpgradeScriptFailed {
            get {
                return ResourceManager.GetString("Error_GetUpgradeScriptFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the wrapping data object..
        /// </summary>
        internal static string Error_GetWrapDataObjectFailed {
            get {
                return ResourceManager.GetString("Error_GetWrapDataObjectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export route to GRF because break stop have no location..
        /// </summary>
        internal static string Error_GrfExporterNoBreakStopLocation {
            get {
                return ResourceManager.GetString("Error_GrfExporterNoBreakStopLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export route to GRF because some stops have no location..
        /// </summary>
        internal static string Error_GrfExporterNoLocationForStop {
            get {
                return ResourceManager.GetString("Error_GrfExporterNoLocationForStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host URI should not be empty..
        /// </summary>
        internal static string Error_HostNameIsEmpty {
            get {
                return ResourceManager.GetString("Error_HostNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal route operation error..
        /// </summary>
        internal static string Error_InternalRouteError {
            get {
                return ResourceManager.GetString("Error_InternalRouteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Sync Profile Name is not set..
        /// </summary>
        internal static string Error_InvalidActiveSyncProfileName {
            get {
                return ResourceManager.GetString("Error_InvalidActiveSyncProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;No error information returned in the REST response&gt;.
        /// </summary>
        internal static string Error_InvalidArcgisRestResponse {
            get {
                return ResourceManager.GetString("Error_InvalidArcgisRestResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrier Effect is not set..
        /// </summary>
        internal static string Error_InvalidBarrierEffect {
            get {
                return ResourceManager.GetString("Error_InvalidBarrierEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay time must be greater than or equal to zero and less than or equal to 1 year..
        /// </summary>
        internal static string Error_InvalidBarrierEffectDelayTime {
            get {
                return ResourceManager.GetString("Error_InvalidBarrierEffectDelayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} break duration must be greater than zero and less than or equal to 1 year..
        /// </summary>
        internal static string Error_InvalidBreakDuration {
            get {
                return ResourceManager.GetString("Error_InvalidBreakDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break GPFeature count is incorrect..
        /// </summary>
        internal static string Error_InvalidBreakGPFeatureCount {
            get {
                return ResourceManager.GetString("Error_InvalidBreakGPFeatureCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} break &apos;After&apos; value must be greater than zero and less than or equal to 1 year..
        /// </summary>
        internal static string Error_InvalidBreakInterval {
            get {
                return ResourceManager.GetString("Error_InvalidBreakInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the routes must have the same type of breaks (either time window based or max work time or max travel time)..
        /// </summary>
        internal static string Error_InvalidBreaksTypes {
            get {
                return ResourceManager.GetString("Error_InvalidBreaksTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} capacity value must be greater than or equal to zero..
        /// </summary>
        internal static string Error_InvalidCapacity {
            get {
                return ResourceManager.GetString("Error_InvalidCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CO2 emission value must be greater than or equal to zero..
        /// </summary>
        internal static string Error_InvalidCo2Emission {
            get {
                return ResourceManager.GetString("Error_InvalidCo2Emission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name or password..
        /// </summary>
        internal static string Error_InvalidCredentials {
            get {
                return ResourceManager.GetString("Error_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} custom property value must be greater than or equal to zero..
        /// </summary>
        internal static string Error_InvalidCustomProperty {
            get {
                return ResourceManager.GetString("Error_InvalidCustomProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data object instance..
        /// </summary>
        internal static string Error_InvalidDataObjectInstance {
            get {
                return ResourceManager.GetString("Error_InvalidDataObjectInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date value..
        /// </summary>
        internal static string Error_InvalidDateTime {
            get {
                return ResourceManager.GetString("Error_InvalidDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing request must contain at least 1 depot..
        /// </summary>
        internal static string Error_InvalidDepotsNum {
            get {
                return ResourceManager.GetString("Error_InvalidDepotsNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid directions number..
        /// </summary>
        internal static string Error_InvalidDirectionsNumber {
            get {
                return ResourceManager.GetString("Error_InvalidDirectionsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address is invalid..
        /// </summary>
        internal static string Error_InvalidEMail {
            get {
                return ResourceManager.GetString("Error_InvalidEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Cost must be greater than or equal to zero and less than or equal to {5}..
        /// </summary>
        internal static string Error_InvalidFixedCost {
            get {
                return ResourceManager.GetString("Error_InvalidFixedCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Folder path is invalid..
        /// </summary>
        internal static string Error_InvalidFolderPath {
            get {
                return ResourceManager.GetString("Error_InvalidFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid vehicle FuelConsumption value..
        /// </summary>
        internal static string Error_InvalidFuelConsumptionValue {
            get {
                return ResourceManager.GetString("Error_InvalidFuelConsumptionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost per kilometer (Fuel Price * Fuel Economy * 100 / 1.609344) must be greater than or equal to zero and less than or equal to {0}..
        /// </summary>
        internal static string Error_InvalidFuelEconomyMetric {
            get {
                return ResourceManager.GetString("Error_InvalidFuelEconomyMetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost per mile (Fuel Price / Fuel Economy) must be greater than or equal to zero and less than or equal to {0}..
        /// </summary>
        internal static string Error_InvalidFuelEconomyUS {
            get {
                return ResourceManager.GetString("Error_InvalidFuelEconomyUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Economy must be greater than zero..
        /// </summary>
        internal static string Error_InvalidFuelEconomyValue {
            get {
                return ResourceManager.GetString("Error_InvalidFuelEconomyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price must be greater than or equal to zero..
        /// </summary>
        internal static string Error_InvalidFuelPrice {
            get {
                return ResourceManager.GetString("Error_InvalidFuelPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Type must be selected..
        /// </summary>
        internal static string Error_InvalidFuelType {
            get {
                return ResourceManager.GetString("Error_InvalidFuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrier shape is incomplete..
        /// </summary>
        internal static string Error_InvalidGeometryBarrier {
            get {
                return ResourceManager.GetString("Error_InvalidGeometryBarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone shape is incomplete..
        /// </summary>
        internal static string Error_InvalidGeometryZone {
            get {
                return ResourceManager.GetString("Error_InvalidGeometryZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to correlate output GP feature to data object..
        /// </summary>
        internal static string Error_InvalidGPFeatureMapping {
            get {
                return ResourceManager.GetString("Error_InvalidGPFeatureMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON response string..
        /// </summary>
        internal static string Error_InvalidJsonResponseString {
            get {
                return ResourceManager.GetString("Error_InvalidJsonResponseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get valid license data..
        /// </summary>
        internal static string Error_InvalidLicenseData {
            get {
                return ResourceManager.GetString("Error_InvalidLicenseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License component must be signed by ESRI..
        /// </summary>
        internal static string Error_InvalidLicenserSignature {
            get {
                return ResourceManager.GetString("Error_InvalidLicenserSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Orders must be greater than zero and less than or equal to one thousand..
        /// </summary>
        internal static string Error_InvalidMaxOrder {
            get {
                return ResourceManager.GetString("Error_InvalidMaxOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Total Duration must be greater than or equal to zero and less than or equal to 1 year..
        /// </summary>
        internal static string Error_InvalidMaxTotalDuration {
            get {
                return ResourceManager.GetString("Error_InvalidMaxTotalDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Travel Distance must be greater than or equal to zero and less than or equal to {0}..
        /// </summary>
        internal static string Error_InvalidMaxTravelDistance {
            get {
                return ResourceManager.GetString("Error_InvalidMaxTravelDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Travel Duration must be greater than or equal to zero and less than or equal to 1 year..
        /// </summary>
        internal static string Error_InvalidMaxTravelDuration {
            get {
                return ResourceManager.GetString("Error_InvalidMaxTravelDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Travel Duration must be less than or equal to Max Total Duration..
        /// </summary>
        internal static string Error_InvalidMaxTravelDuration2 {
            get {
                return ResourceManager.GetString("Error_InvalidMaxTravelDuration2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Violation Time must be greater than or equal to zero and less than or equal to 1 year..
        /// </summary>
        internal static string Error_InvalidMaxViolationTime {
            get {
                return ResourceManager.GetString("Error_InvalidMaxViolationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid network attribute/parameter name..
        /// </summary>
        internal static string Error_InvalidNetworkAttr {
            get {
                return ResourceManager.GetString("Error_InvalidNetworkAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid network attribute: {0}, {1}.
        /// </summary>
        internal static string Error_InvalidNetworkAttr2 {
            get {
                return ResourceManager.GetString("Error_InvalidNetworkAttr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent type of network parameter value..
        /// </summary>
        internal static string Error_InvalidNetworkParamType {
            get {
                return ResourceManager.GetString("Error_InvalidNetworkParamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least one order to assign..
        /// </summary>
        internal static string Error_InvalidOrdersToAssignCount {
            get {
                return ResourceManager.GetString("Error_InvalidOrdersToAssignCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Hour OT Salary must be greater than or equal to zero and less than or equal to {5}..
        /// </summary>
        internal static string Error_InvalidPerHourOTSalary {
            get {
                return ResourceManager.GetString("Error_InvalidPerHourOTSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Hour OT Salary must be greater than or equal to Per Hour Salary..
        /// </summary>
        internal static string Error_InvalidPerHourOTSalary2 {
            get {
                return ResourceManager.GetString("Error_InvalidPerHourOTSalary2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Hour Salary must be greater than zero and less than or equal to {5}..
        /// </summary>
        internal static string Error_InvalidPerHourSalary {
            get {
                return ResourceManager.GetString("Error_InvalidPerHourSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point parameter string &apos;{0}&apos; should contain two and only two point coordinates..
        /// </summary>
        internal static string Error_InvalidPointParameterFormat {
            get {
                return ResourceManager.GetString("Error_InvalidPointParameterFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver has errors..
        /// </summary>
        internal static string Error_InvalidRefObjDriver {
            get {
                return ResourceManager.GetString("Error_InvalidRefObjDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver is deleted..
        /// </summary>
        internal static string Error_InvalidRefObjDriverIsDeleted {
            get {
                return ResourceManager.GetString("Error_InvalidRefObjDriverIsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Depot has errors..
        /// </summary>
        internal static string Error_InvalidRefObjEndLocation {
            get {
                return ResourceManager.GetString("Error_InvalidRefObjEndLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Depot is deleted..
        /// </summary>
        internal static string Error_InvalidRefObjEndLocationIsDeleted {
            get {
                return ResourceManager.GetString("Error_InvalidRefObjEndLocationIsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Type has errors..
        /// </summary>
        internal static string Error_InvalidRefObjFuelType {
            get {
                return ResourceManager.GetString("Error_InvalidRefObjFuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Device has errors..
        /// </summary>
        internal static string Error_InvalidRefObjMobileDevice {
            get {
                return ResourceManager.GetString("Error_InvalidRefObjMobileDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Depot has errors..
        /// </summary>
        internal static string Error_InvalidRefObjStartLocation {
            get {
                return ResourceManager.GetString("Error_InvalidRefObjStartLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Depot is deleted..
        /// </summary>
        internal static string Error_InvalidRefObjStartLocationIsDeleted {
            get {
                return ResourceManager.GetString("Error_InvalidRefObjStartLocationIsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle has errors..
        /// </summary>
        internal static string Error_InvalidRefObjVehicle {
            get {
                return ResourceManager.GetString("Error_InvalidRefObjVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle is deleted..
        /// </summary>
        internal static string Error_InvalidRefObjVehicleIsDeleted {
            get {
                return ResourceManager.GetString("Error_InvalidRefObjVehicleIsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid region information..
        /// </summary>
        internal static string Error_InvalidRegionInformation {
            get {
                return ResourceManager.GetString("Error_InvalidRegionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid restriction name: {0}.
        /// </summary>
        internal static string Error_InvalidRestrictionName {
            get {
                return ResourceManager.GetString("Error_InvalidRestrictionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing response contains invalid data..
        /// </summary>
        internal static string Error_InvalidResultJobResponse {
            get {
                return ResourceManager.GetString("Error_InvalidResultJobResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing request must contain at least 1 route..
        /// </summary>
        internal static string Error_InvalidRoutesNum {
            get {
                return ResourceManager.GetString("Error_InvalidRoutesNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of routes..
        /// </summary>
        internal static string Error_InvalidRoutesNumber {
            get {
                return ResourceManager.GetString("Error_InvalidRoutesNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least one unlocked route to sequence..
        /// </summary>
        internal static string Error_InvalidRoutesToSequenceCount {
            get {
                return ResourceManager.GetString("Error_InvalidRoutesToSequenceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route (id={0}) cannot be sequenced since it does not belong to processing schedule..
        /// </summary>
        internal static string Error_InvalidRouteToSequence {
            get {
                return ResourceManager.GetString("Error_InvalidRouteToSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid routing configuration..
        /// </summary>
        internal static string Error_InvalidRoutingConfig {
            get {
                return ResourceManager.GetString("Error_InvalidRoutingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing operation cannot be executed since some input data objects are invalid..
        /// </summary>
        internal static string Error_InvalidScheduleData {
            get {
                return ResourceManager.GetString("Error_InvalidScheduleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Time must be greater than or equal to zero and less than or equal to 1 year..
        /// </summary>
        internal static string Error_InvalidServiceTime {
            get {
                return ResourceManager.GetString("Error_InvalidServiceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings are not valid..
        /// </summary>
        internal static string Error_InvalidSettings {
            get {
                return ResourceManager.GetString("Error_InvalidSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slowdown % must be greater than or equal to {0}% and less than {1}%. If you need {2}% slowdown select Block Travel..
        /// </summary>
        internal static string Error_InvalidSlowdown {
            get {
                return ResourceManager.GetString("Error_InvalidSlowdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed up % must be greater than or equal to {0}% and less than or equal to {1}%..
        /// </summary>
        internal static string Error_InvalidSpeedUp {
            get {
                return ResourceManager.GetString("Error_InvalidSpeedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route (id={0}) plannedDate differs from the schedule&apos;s one..
        /// </summary>
        internal static string Error_InvalidTargetRouteDate {
            get {
                return ResourceManager.GetString("Error_InvalidTargetRouteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be one target route..
        /// </summary>
        internal static string Error_InvalidTargetRoutesCount {
            get {
                return ResourceManager.GetString("Error_InvalidTargetRoutesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid target sequence value..
        /// </summary>
        internal static string Error_InvalidTargetSequence {
            get {
                return ResourceManager.GetString("Error_InvalidTargetSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time At End must be greater than or equal to zero and less than or equal to 1 year..
        /// </summary>
        internal static string Error_InvalidTimeAtEnd {
            get {
                return ResourceManager.GetString("Error_InvalidTimeAtEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time At Renewal must be greater than or equal to zero and less than or equal to 1 year..
        /// </summary>
        internal static string Error_InvalidTimeAtRenewal {
            get {
                return ResourceManager.GetString("Error_InvalidTimeAtRenewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time At Start must be greater than or equal to zero and less than or equal to 1 year..
        /// </summary>
        internal static string Error_InvalidTimeAtStart {
            get {
                return ResourceManager.GetString("Error_InvalidTimeAtStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Before OT must be greater than or equal to zero and less than or equal to 1 year..
        /// </summary>
        internal static string Error_InvalidTimeBeforeOT {
            get {
                return ResourceManager.GetString("Error_InvalidTimeBeforeOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid tracking configuration..
        /// </summary>
        internal static string Error_InvalidTrackingConfig {
            get {
                return ResourceManager.GetString("Error_InvalidTrackingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mobile device IDs number in tracking service response..
        /// </summary>
        internal static string Error_InvalidTSDevicesIds {
            get {
                return ResourceManager.GetString("Error_InvalidTSDevicesIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid vehicle IDs number in tracking service response..
        /// </summary>
        internal static string Error_InvalidTSVehicleIds {
            get {
                return ResourceManager.GetString("Error_InvalidTSVehicleIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least one unlocked order to assign..
        /// </summary>
        internal static string Error_InvalidUnlockedOrdersToAssignCount {
            get {
                return ResourceManager.GetString("Error_InvalidUnlockedOrdersToAssignCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least one unlocked target route..
        /// </summary>
        internal static string Error_InvalidUnlockedTargetRoutesCount {
            get {
                return ResourceManager.GetString("Error_InvalidUnlockedTargetRoutesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Routing request..
        /// </summary>
        internal static string Error_InvalidVrpRequest {
            get {
                return ResourceManager.GetString("Error_InvalidVrpRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but you are not licensed to run the application. Contact your vendor..
        /// </summary>
        internal static string Error_LicenseComponentNotFound {
            get {
                return ResourceManager.GetString("Error_LicenseComponentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License component is not set..
        /// </summary>
        internal static string Error_LicenseComponentNotSet {
            get {
                return ResourceManager.GetString("Error_LicenseComponentNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License is expired..
        /// </summary>
        internal static string Error_LicenseIsExpired {
            get {
                return ResourceManager.GetString("Error_LicenseIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License is not activated..
        /// </summary>
        internal static string Error_LicenseNotActivated {
            get {
                return ResourceManager.GetString("Error_LicenseNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error communicating with licensing service..
        /// </summary>
        internal static string Error_LicenseServiceCommunication {
            get {
                return ResourceManager.GetString("Error_LicenseServiceCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depot (id={0}) is not geocoded..
        /// </summary>
        internal static string Error_LocationIsUngeocoded {
            get {
                return ResourceManager.GetString("Error_LocationIsUngeocoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depot is located too far from the nearest road..
        /// </summary>
        internal static string Error_LocationNotFoundOnNetworkViolationMessage {
            get {
                return ResourceManager.GetString("Error_LocationNotFoundOnNetworkViolationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depot must be geocoded..
        /// </summary>
        internal static string Error_LocationNotGeocoded {
            get {
                return ResourceManager.GetString("Error_LocationNotGeocoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect user name or password..
        /// </summary>
        internal static string Error_LoginFailed {
            get {
                return ResourceManager.GetString("Error_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license allows a maximum of {0} order(s) and you have {1} order(s) for this day..
        /// </summary>
        internal static string Error_MaxOrdersPermission {
            get {
                return ResourceManager.GetString("Error_MaxOrdersPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license allows a maximum of {0} route(s) and you have {1} route(s) for this schedule..
        /// </summary>
        internal static string Error_MaxRoutesPermission {
            get {
                return ResourceManager.GetString("Error_MaxRoutesPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile device name is too long..
        /// </summary>
        internal static string Error_MobileDeviceNameIsTooLong {
            get {
                return ResourceManager.GetString("Error_MobileDeviceNameIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No allowed user role found..
        /// </summary>
        internal static string Error_NoAllowedUserRole {
            get {
                return ResourceManager.GetString("Error_NoAllowedUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults Capacities info is absent..
        /// </summary>
        internal static string Error_NoDefaultsCapacities {
            get {
                return ResourceManager.GetString("Error_NoDefaultsCapacities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults Driver info is absent..
        /// </summary>
        internal static string Error_NoDefaultsDriver {
            get {
                return ResourceManager.GetString("Error_NoDefaultsDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults Fuel Types info is absent..
        /// </summary>
        internal static string Error_NoDefaultsFuelTypes {
            get {
                return ResourceManager.GetString("Error_NoDefaultsFuelTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults Location info is absent..
        /// </summary>
        internal static string Error_NoDefaultsLocation {
            get {
                return ResourceManager.GetString("Error_NoDefaultsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults Order info is absent..
        /// </summary>
        internal static string Error_NoDefaultsOrder {
            get {
                return ResourceManager.GetString("Error_NoDefaultsOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults Order Custom Properies info is absent..
        /// </summary>
        internal static string Error_NoDefaultsOrderCustomProperties {
            get {
                return ResourceManager.GetString("Error_NoDefaultsOrderCustomProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults Route info is absent..
        /// </summary>
        internal static string Error_NoDefaultsRoute {
            get {
                return ResourceManager.GetString("Error_NoDefaultsRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults Vehicle info is absent..
        /// </summary>
        internal static string Error_NoDefaultsVehicle {
            get {
                return ResourceManager.GetString("Error_NoDefaultsVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion field name is not set..
        /// </summary>
        internal static string Error_NoDeletionFieldName {
            get {
                return ResourceManager.GetString("Error_NoDeletionFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get directions for route (id={0})..
        /// </summary>
        internal static string Error_NoDirectionsForRoute {
            get {
                return ResourceManager.GetString("Error_NoDirectionsForRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity key name is not set..
        /// </summary>
        internal static string Error_NoEntityKeyName {
            get {
                return ResourceManager.GetString("Error_NoEntityKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one day of week must be set..
        /// </summary>
        internal static string Error_NotSelectedDaysOfWeek {
            get {
                return ResourceManager.GetString("Error_NotSelectedDaysOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver must be selected..
        /// </summary>
        internal static string Error_NotSetReferenceObjectDriver {
            get {
                return ResourceManager.GetString("Error_NotSetReferenceObjectDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either Start or End Depot must be selected..
        /// </summary>
        internal static string Error_NotSetReferenceObjectLocations {
            get {
                return ResourceManager.GetString("Error_NotSetReferenceObjectLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle must be selected..
        /// </summary>
        internal static string Error_NotSetReferenceObjectVehicle {
            get {
                return ResourceManager.GetString("Error_NotSetReferenceObjectVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the {0}. This is a required field..
        /// </summary>
        internal static string Error_NullName {
            get {
                return ResourceManager.GetString("Error_NullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create new project. Total length of order custom properties is too long..
        /// </summary>
        internal static string Error_OrderCustomPropTooLong {
            get {
                return ResourceManager.GetString("Error_OrderCustomPropTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order (id={0}) is not geocoded..
        /// </summary>
        internal static string Error_OrderIsUngeocoded {
            get {
                return ResourceManager.GetString("Error_OrderIsUngeocoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is located too far from the nearest road..
        /// </summary>
        internal static string Error_OrderNotFoundOnNetworkViolationMessage {
            get {
                return ResourceManager.GetString("Error_OrderNotFoundOnNetworkViolationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order must be geocoded..
        /// </summary>
        internal static string Error_OrderNotGeocoded {
            get {
                return ResourceManager.GetString("Error_OrderNotGeocoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove order since it has associated stop objects..
        /// </summary>
        internal static string Error_OrderRemovalFailed {
            get {
                return ResourceManager.GetString("Error_OrderRemovalFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Window 2 must occur later than Time Window..
        /// </summary>
        internal static string Error_OrderTW1LaterTW2 {
            get {
                return ResourceManager.GetString("Error_OrderTW1LaterTW2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Windows must not overlap..
        /// </summary>
        internal static string Error_OrderTWOverlapped {
            get {
                return ResourceManager.GetString("Error_OrderTWOverlapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize polyline object..
        /// </summary>
        internal static string Error_PolylineDeserializationFailed {
            get {
                return ResourceManager.GetString("Error_PolylineDeserializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current project is not set..
        /// </summary>
        internal static string Error_ProjectIsNotSet {
            get {
                return ResourceManager.GetString("Error_ProjectIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-only collection cannot be modified..
        /// </summary>
        internal static string Error_ReadOnlyCollectionChange {
            get {
                return ResourceManager.GetString("Error_ReadOnlyCollectionChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal Depot &apos;{0}&apos; has errors..
        /// </summary>
        internal static string Error_RenewalLocationsErrorFormat {
            get {
                return ResourceManager.GetString("Error_RenewalLocationsErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal Depot &apos;{0}&apos; is deleted..
        /// </summary>
        internal static string Error_RenewalLocationsIsDeletedErrorFormat {
            get {
                return ResourceManager.GetString("Error_RenewalLocationsIsDeletedErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} name &apos;{1}&apos; is reserved. Please select another name..
        /// </summary>
        internal static string Error_ReservedCustomOrderPropertyName {
            get {
                return ResourceManager.GetString("Error_ReservedCustomOrderPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restriction cannot be edited..
        /// </summary>
        internal static string Error_RestrictionIsNotEditable {
            get {
                return ResourceManager.GetString("Error_RestrictionIsNotEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver is already in use for other route(s) for the day during the same time window..
        /// </summary>
        internal static string Error_RouteContainsInvalidDriver {
            get {
                return ResourceManager.GetString("Error_RouteContainsInvalidDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle is already in use for other route(s) for the day during the same time window..
        /// </summary>
        internal static string Error_RouteContainsInvalidVehicle {
            get {
                return ResourceManager.GetString("Error_RouteContainsInvalidVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This route belong to schedule, it&apos;s owner collection cant be set explicity..
        /// </summary>
        internal static string Error_RouteIsScheduled {
            get {
                return ResourceManager.GetString("Error_RouteIsScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove route since it has associated route result objects..
        /// </summary>
        internal static string Error_RouteRemovalFailed {
            get {
                return ResourceManager.GetString("Error_RouteRemovalFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all routes belong to the same schedule..
        /// </summary>
        internal static string Error_RoutesBelongToDifSchedules {
            get {
                return ResourceManager.GetString("Error_RoutesBelongToDifSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes cannot be deployed since they do not contain required tracking information..
        /// </summary>
        internal static string Error_RoutesDeployment {
            get {
                return ResourceManager.GetString("Error_RoutesDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize Route service..
        /// </summary>
        internal static string Error_RouteServiceInit {
            get {
                return ResourceManager.GetString("Error_RouteServiceInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earliest start time must occur before the Start Depot&apos;s close time..
        /// </summary>
        internal static string Error_RouteStartAfterLocClose {
            get {
                return ResourceManager.GetString("Error_RouteStartAfterLocClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time Window cannot be wideopen..
        /// </summary>
        internal static string Error_RouteStartTWCannotWideopen {
            get {
                return ResourceManager.GetString("Error_RouteStartTWCannotWideopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest start time must occur after the Start Depot&apos;s open time..
        /// </summary>
        internal static string Error_RouteStopBeforeLocOpen {
            get {
                return ResourceManager.GetString("Error_RouteStopBeforeLocOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate route because stop where break has occured is missing..
        /// </summary>
        internal static string Error_RoutingMissingBreakStop {
            get {
                return ResourceManager.GetString("Error_RoutingMissingBreakStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule date is not set..
        /// </summary>
        internal static string Error_ScheduleDateNotSet {
            get {
                return ResourceManager.GetString("Error_ScheduleDateNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver is already in use for other route(s) for the day during the same time window..
        /// </summary>
        internal static string Error_ScheduledRouteContainsInvalidDriver {
            get {
                return ResourceManager.GetString("Error_ScheduledRouteContainsInvalidDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle is already in use for other route(s) for the day during the same time window..
        /// </summary>
        internal static string Error_ScheduledRouteContainsInvalidVehicle {
            get {
                return ResourceManager.GetString("Error_ScheduledRouteContainsInvalidVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule is not set..
        /// </summary>
        internal static string Error_ScheduleNotSet {
            get {
                return ResourceManager.GetString("Error_ScheduleNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server &quot;{0}&quot; is in unavailable state. Check your connection or configuration file..
        /// </summary>
        internal static string Error_ServerInUnavailableState {
            get {
                return ResourceManager.GetString("Error_ServerInUnavailableState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} server is busy now. Please retry your request later..
        /// </summary>
        internal static string Error_ServerTemporaryUnavailable {
            get {
                return ResourceManager.GetString("Error_ServerTemporaryUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed to {0}. Please try re-entering your username and password..
        /// </summary>
        internal static string Error_ServerUnauthorized {
            get {
                return ResourceManager.GetString("Error_ServerUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Planner cannot connect to {0}. Please check your network connection..
        /// </summary>
        internal static string Error_ServerUnavailable {
            get {
                return ResourceManager.GetString("Error_ServerUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User cancelled service initialization..
        /// </summary>
        internal static string Error_ServiceInitCancelled {
            get {
                return ResourceManager.GetString("Error_ServiceInitCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize service..
        /// </summary>
        internal static string Error_ServiceInitFailed {
            get {
                return ResourceManager.GetString("Error_ServiceInitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Date must be the same or later than Start Date..
        /// </summary>
        internal static string Error_StartDateLaterFinishDate {
            get {
                return ResourceManager.GetString("Error_StartDateLaterFinishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one export operation per moment supported..
        /// </summary>
        internal static string Error_StartExportTwice {
            get {
                return ResourceManager.GetString("Error_StartExportTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop&apos;s &quot;Name&quot;property is read-only..
        /// </summary>
        internal static string Error_StopNameReadOnly {
            get {
                return ResourceManager.GetString("Error_StopNameReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is not responding, please resubmitt your work, if this problem persists please contact ESRI support..
        /// </summary>
        internal static string Error_SubmitJob {
            get {
                return ResourceManager.GetString("Error_SubmitJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to submit job..
        /// </summary>
        internal static string Error_SubmitJobFailed {
            get {
                return ResourceManager.GetString("Error_SubmitJobFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to execute one or more parallel tasks..
        /// </summary>
        internal static string Error_ThreadingExecutionFailed {
            get {
                return ResourceManager.GetString("Error_ThreadingExecutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of inner exceptions is a null reference..
        /// </summary>
        internal static string Error_ThreadingNullInnerException {
            get {
                return ResourceManager.GetString("Error_ThreadingNullInnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} break can&apos;t have same &quot;Break After&quot; value as {1} break..
        /// </summary>
        internal static string Error_TimeIntervalsAreEqual {
            get {
                return ResourceManager.GetString("Error_TimeIntervalsAreEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} break and {1} break will overlap..
        /// </summary>
        internal static string Error_TimeIntervalsPlusDurationExceed {
            get {
                return ResourceManager.GetString("Error_TimeIntervalsPlusDurationExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of time window &apos;From&apos; time span should be less than 24 hours..
        /// </summary>
        internal static string Error_TimeWindowFromParameter {
            get {
                return ResourceManager.GetString("Error_TimeWindowFromParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} break time window must not overlap the time window of {1} break..
        /// </summary>
        internal static string Error_TimeWindowOverlap {
            get {
                return ResourceManager.GetString("Error_TimeWindowOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter(s) of Time Window..
        /// </summary>
        internal static string Error_TimeWindowParameters {
            get {
                return ResourceManager.GetString("Error_TimeWindowParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} break time window plus duration must not overlap the time window of {1} break..
        /// </summary>
        internal static string Error_TimeWindowPlusDurationOverlap {
            get {
                return ResourceManager.GetString("Error_TimeWindowPlusDurationOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of time window &apos;To&apos; time span should be less than 24 hours..
        /// </summary>
        internal static string Error_TimeWindowToParameter {
            get {
                return ResourceManager.GetString("Error_TimeWindowToParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server does not support token-based authentication..
        /// </summary>
        internal static string Error_TokenAuthNotSupported {
            get {
                return ResourceManager.GetString("Error_TokenAuthNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown violation type..
        /// </summary>
        internal static string Error_UnknownViolationType {
            get {
                return ResourceManager.GetString("Error_UnknownViolationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received unknown error from the Tracking Service..
        /// </summary>
        internal static string Error_UnspecifiedTrackingServiceError {
            get {
                return ResourceManager.GetString("Error_UnspecifiedTrackingServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported associated object value..
        /// </summary>
        internal static string Error_UnsupportedAssocObject {
            get {
                return ResourceManager.GetString("Error_UnsupportedAssocObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported network attribute units..
        /// </summary>
        internal static string Error_UnsupportedAttrUnits {
            get {
                return ResourceManager.GetString("Error_UnsupportedAttrUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported network attribute usage type..
        /// </summary>
        internal static string Error_UnsupportedAttrUsageType {
            get {
                return ResourceManager.GetString("Error_UnsupportedAttrUsageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression nodes of type &apos;{0}&apos; are not supported..
        /// </summary>
        internal static string Error_UnsupportedExpressionTypeFormat {
            get {
                return ResourceManager.GetString("Error_UnsupportedExpressionTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize geometry object: unsupported object type..
        /// </summary>
        internal static string Error_UnsupportedGPGeometryObject {
            get {
                return ResourceManager.GetString("Error_UnsupportedGPGeometryObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported HTTP binding type..
        /// </summary>
        internal static string Error_UnsupportedHttpBinding {
            get {
                return ResourceManager.GetString("Error_UnsupportedHttpBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project is not compatible with this version of Route Planner..
        /// </summary>
        internal static string Error_UnsupportedSchemeVersion {
            get {
                return ResourceManager.GetString("Error_UnsupportedSchemeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled by user..
        /// </summary>
        internal static string Error_UserCancel {
            get {
                return ResourceManager.GetString("Error_UserCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All route&apos;s breaks cannot be visited. Try to change start time window or increase max total duration..
        /// </summary>
        internal static string Error_VRP_AllBreaksCannotBeVisited {
            get {
                return ResourceManager.GetString("Error_VRP_AllBreaksCannotBeVisited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route&apos;s break cannot be visited. Try to change start time window or increase max total duration..
        /// </summary>
        internal static string Error_VRP_BreakCannotBeVisited {
            get {
                return ResourceManager.GetString("Error_VRP_BreakCannotBeVisited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End depot cannot be serviced. Try to decrease route time at end or increase end depot time window..
        /// </summary>
        internal static string Error_VRP_FinishLocationCannotBeServiced {
            get {
                return ResourceManager.GetString("Error_VRP_FinishLocationCannotBeServiced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End depot cannot be visited. Try to increase route max total duration or change End depot time window..
        /// </summary>
        internal static string Error_VRP_FinishLocationCannotBeVisited {
            get {
                return ResourceManager.GetString("Error_VRP_FinishLocationCannotBeVisited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last break cannot be visited. Try to increase route max total duration or decrease break duration..
        /// </summary>
        internal static string Error_VRP_LastBreakCannotBeVisited {
            get {
                return ResourceManager.GetString("Error_VRP_LastBreakCannotBeVisited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route max total duration is less or equal then time, which route will spend at start and end locations..
        /// </summary>
        internal static string Error_VRP_MaxTotalDurationIsSmall {
            get {
                return ResourceManager.GetString("Error_VRP_MaxTotalDurationIsSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start depot cannot be serviced. Try to decrease route time at start or increase start depot time window..
        /// </summary>
        internal static string Error_VRP_StartLocationCannotBeServiced {
            get {
                return ResourceManager.GetString("Error_VRP_StartLocationCannotBeServiced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start depot cannot be visited. Try to change route start time window or start depot time window..
        /// </summary>
        internal static string Error_VRP_StartLocationCannotBeVisited {
            get {
                return ResourceManager.GetString("Error_VRP_StartLocationCannotBeVisited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaks starting from {0} cannot be visited. Try to increase route max total duration or decrease breaks duration..
        /// </summary>
        internal static string Error_VRP_TheBreakAndAllAfterItCannotBeVisited {
            get {
                return ResourceManager.GetString("Error_VRP_TheBreakAndAllAfterItCannotBeVisited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize Routing service..
        /// </summary>
        internal static string Error_VRPServiceInit {
            get {
                return ResourceManager.GetString("Error_VRPServiceInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong configuration file format..
        /// </summary>
        internal static string Error_WrongConfigFormat {
            get {
                return ResourceManager.GetString("Error_WrongConfigFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone &apos;{0}&apos; has errors..
        /// </summary>
        internal static string Error_ZonesErrorFormat {
            get {
                return ResourceManager.GetString("Error_ZonesErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error_RouteIsScheduled.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line/Shape barriers are not supported now and have been skipped..
        /// </summary>
        internal static string Warning_BarriersNotSupported {
            get {
                return ResourceManager.GetString("Warning_BarriersNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay point barriers are not supported now and have been skipped..
        /// </summary>
        internal static string Warning_DelayPointBarriersNotSupported {
            get {
                return ResourceManager.GetString("Warning_DelayPointBarriersNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking configuration settings wasn&apos;t speicified..
        /// </summary>
        internal static string Warning_NoTrackingConfig {
            get {
                return ResourceManager.GetString("Warning_NoTrackingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U-turn policy &quot;at dead ends and intersections&quot; is not supported now and it has been replaced with &quot;at dead ends&quot;..
        /// </summary>
        internal static string Warning_UTurnPolicyNotSupported {
            get {
                return ResourceManager.GetString("Warning_UTurnPolicyNotSupported", resourceCulture);
            }
        }
    }
}
